### ISSUE TITLE
Final Review

### ISSUE THREAD

**Issue by gtrebilcock** [pdraiter/course-evaluations#10]
The project is about course evaluations filled out by Cornell students and exploring ways to deliver constructive feedback to professors. The data this group is using includes the course evaluations provided to them by the Cornell Engineering department. The goal of the project is to find an efficient way to deliver course evaluations from students to professors in a way such that professors can read all the feedback without having some of the reviews that have no constructive feedback in them. 

The first  aspect of this project that I liked was the presentation, which includes the style of the paper and the visualization of data. This made the paper easier to read and digest information as compared to other projects. The second aspect I liked was the variety of models put to use. The final aspect I liked was that the group was able to come to interesting conclusions which might tilt slightly philosophical, but the ability to recognize negative comments easier than positive comments.

One area for improvement would be a deeper discussion around how to classify negative vs positive comments. Intentions are hard to decipher from text alone and I think this delves into the philosophical realm much more than computer science. Another area for improvement that I as a reader wondered was how these models perform on other data sets that researchers use. Essentially I wondered what was the industry standard and what sort of error we should expect to see, this would help contextualize the accuracy of the models given. Finally, I would expect other research papers to have been written on the same subject yet there was not a bibliography at the end of the paper. Presumably there were other sources of information that influenced this paper so it would be nice to be able to read these as well.

**Comment by pdraiter** [comment]
Hello, gtrebilcock,

Thank you for your feedback throughout the semester. I appreciate it and tried to incorporate the suggestions wherever I could.

I have added a bilbliography section at the end.

Thanks,
Raiter
